version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_LINK: ${DISCORD_LINK}
      BLACKLIST_CHAN_ID: ${BLACKLIST_CHAN_ID}
      LOGS_CHAN_ID: ${LOGS_CHAN_ID}
      LIVE_CHAN_ID: ${LIVE_CHAN_ID}
      VIDEO_CHAN_ID: ${VIDEO_CHAN_ID}
      NO_LIVE_CHAN_ID: ${NO_LIVE_CHAN_ID}
      ADMIN_ROLE_IDS: ${ADMIN_ROLE_IDS}
      PING_YOUTUBE_VIDEO_ROLE_IDS: ${PING_YOUTUBE_VIDEO_ROLE_IDS}
      PING_YOUTUBE_LIVE_ROLE_IDS: ${PING_YOUTUBE_LIVE_ROLE_IDS}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      YOUTUBE_CHANNEL_ID: ${YOUTUBE_CHANNEL_ID}
      YOUTUBE_LINK: ${YOUTUBE_LINK}
