version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./bot
    restart: unless-stopped
    environment:
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_LINK: ${DISCORD_LINK}
      BLACKLIST_CHAN_ID: ${BLACKLIST_CHAN_ID}
      LOGS_CHAN_ID: ${LOGS_CHAN_ID}
      LIVE_CHAN_ID: ${LIVE_CHAN_ID}
      VIDEO_CHAN_ID: ${VIDEO_CHAN_ID}
      NO_LIVE_CHAN_ID: ${NO_LIVE_CHAN_ID}
      ADMIN_ROLE_IDS: ${ADMIN_ROLE_IDS}
      PING_YOUTUBE_VIDEO_ROLE_IDS: ${PING_YOUTUBE_VIDEO_ROLE_IDS}
      PING_YOUTUBE_LIVE_ROLE_IDS: ${PING_YOUTUBE_LIVE_ROLE_IDS}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      YOUTUBE_CHANNEL_ID: ${YOUTUBE_CHANNEL_ID}
      YOUTUBE_LINK: ${YOUTUBE_LINK}

  postgres:
   image: postgres:latest
   restart: unless-stopped
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -V"]
     interval: 10s
     timeout: 5s
     retries: 5
   volumes:
     - mysql_data:/var/lib/mysql
   environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
   ports:
     - 35000:5432
   networks:
     - db

  # The Postgres Admin tool if we want to run some custom queries and so on against our Database
  postgres_admin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    volumes:
      - ./db/pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  mysql_data:
